my_file = open('Text.txt', 'r')
content = my_file.read()
print(f'Текст файла: {content}')
my_file = open('Text.txt', 'r')
content = my_file.readlines()
print(f'Количество строк: {len(content)}')
my_file = open('Text.txt', 'r')
content = my_file.readlines()
for i in range(len(content)):
    print(f'Количество символов {i + 1} - строка: {len(content[i])}')
my_file = open('Text.txt', 'r')
content = my_file.read()
content = content.split()
print(f'Количество слов: {len(content)}')
my_file.close()